services:
  amr-ros-dev-files:
    extends:
      file: /home/zach/code/robotics/ros/amr_ros/docker/compose.yaml
      service: dev
    image: amr-ros-dev-files
    container_name: amr-ros-dev-files
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        USER: $USER
        DEV_IMAGE: amr-ros-dev
        GIT_NAME: "Zach Lambert"
        GIT_EMAIL: "zachalambert@gmail.com"
    volumes:
      - ./nvim:/home/zach/.config/nvim
      - ./zsh:/home/zach/.config/zsh
    command: sleep infinity
