#!/bin/bash

if ! devcontainer --help > /dev/null
then
  echo "devcontainer CLI not installed"
  exit 1
fi

print_usage() {
  echo "Usage: devcli [build | start | restart]"
}

if [[ $# -ne 1 ]]; then
  print_usage
  exit 1;
fi

additional_features='{
  "ghcr.io/zachlambert/dev-tools/neovim": {},
  "ghcr.io/zachlambert/dev-tools/zsh": {},
  "ghcr.io/zachlambert/dev-tools/zach-dotfiles": {},
  "ghcr.io/zachlambert/dev-tools/maki": {},
  "ghcr.io/anthropics/devcontainer-features/claude-code:1.0": {}
}'

case $1 in
  "build")
    devcontainer build \
      --no-cache \
      --workspace-folder . \
      --additional-features "$additional_features"
    ;;
  "start")
    devcontainer up \
      --workspace-folder . \
      --additional-features "$additional_features" \
      --mount type=bind,source=/home/$USER/.gitconfig,target=/home/$USER/.gitconfig \
      --mount type=bind,source=/home/$USER/.claude,target=/home/$USER/.claude \
      --mount type=bind,source=/home/$USER/.claude.json,target=/home/$USER/.claude.json \
      --mount type=bind,source=/home/$USER/.config/maki,target=/home/$USER/.config/maki \
      --mount type=bind,source=/home/$USER/.local/state/maki,target=/home/$USER/.local/state/maki \
      --remove-existing-container
    ;;
  *)
    print_usage
    ;;
esac
